export const buttons = [
    { label: 'AC', type: 'function' as const },
    { label: '()', type: 'function' as const },
    { label: '%', type: 'function' as const },
    { label: '÷', type: 'operator' as const },
    { label: '7', type: 'number' as const },
    { label: '8', type: 'number' as const },
    { label: '9', type: 'number' as const },
    { label: '×', type: 'operator' as const },
    { label: '4', type: 'number' as const },
    { label: '5', type: 'number' as const },
    { label: '6', type: 'number' as const },
    { label: '+', type: 'operator' as const },
    { label: '1', type: 'number' as const },
    { label: '2', type: 'number' as const },
    { label: '3', type: 'number' as const },
    { label: '-', type: 'operator' as const },
    { label: '.', type: 'number' as const },
    { label: '0', type: 'number' as const },
    { label: '⌫', type: 'function' as const },
    { label: '=', type: 'operator' as const },
  ] as const;